### ISSUE TITLE
Notes keeps going up after game is over

### ISSUE THREAD

**Issue by fulldecent** [verbeeckkristof/WhackAMole-for-Swift#2]
![screen shot 2014-10-15 at 23 19 45](https://cloud.githubusercontent.com/assets/382183/4657083/4f794a88-54e3-11e4-9332-af4b575f3666.png)

**Comment by verbeeckkristof** [comment]
i will look at it, thanks for pointing that out

**Comment by fulldecent** [comment]
Closing, project is dead
